/**
 * @file test_ground_truth.cpp
 * @brief Verify RLE encoder/decoder against ImageMagick PPM ground truth files
 *
 * This program tests that RLE files can be decoded and re-encoded correctly
 * by comparing against PPM files generated by ImageMagick from the original
 * RLE files. These PPM files serve as the "ground truth" for expected output.
 */

#include "rle.hpp"
#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <vector>
#include <string>
#include <algorithm>

// Declare external functions from rle.cpp
icv_image_t* rle_read(FILE *fp);
int rle_write(icv_image_t *bif, FILE *fp);
void bu_free(void *ptr, const char *str);

struct PPMImage {
    size_t width;
    size_t height;
    size_t maxval;
    std::vector<uint16_t> data; // RGB data (16-bit per component)
};

/**
 * Read a PPM file (P6 format - binary) supporting both 8-bit and 16-bit depth
 */
PPMImage* read_ppm(const char* filename) {
    FILE* fp = fopen(filename, "rb");
    if (!fp) {
        std::cerr << "Failed to open PPM file: " << filename << std::endl;
        return nullptr;
    }
    
    PPMImage* img = new PPMImage();
    
    // Read magic number
    char magic[3] = {0};
    if (fscanf(fp, "%2s", magic) != 1 || strcmp(magic, "P6") != 0) {
        std::cerr << "Invalid PPM magic number (expected P6)" << std::endl;
        fclose(fp);
        delete img;
        return nullptr;
    }
    
    // Skip whitespace and comments
    int c;
    while ((c = fgetc(fp)) != EOF && (c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '#')) {
        if (c == '#') {
            while ((c = fgetc(fp)) != EOF && c != '\n');
        }
    }
    ungetc(c, fp);
    
    // Read width and height
    if (fscanf(fp, "%zu %zu", &img->width, &img->height) != 2) {
        std::cerr << "Failed to read PPM dimensions" << std::endl;
        fclose(fp);
        delete img;
        return nullptr;
    }
    
    // Read max value
    int maxval;
    if (fscanf(fp, "%d", &maxval) != 1) {
        std::cerr << "Failed to read PPM maxval" << std::endl;
        fclose(fp);
        delete img;
        return nullptr;
    }
    
    if (maxval != 255 && maxval != 65535) {
        std::cerr << "Unsupported PPM maxval (expected 255 or 65535, got " << maxval << ")" << std::endl;
        fclose(fp);
        delete img;
        return nullptr;
    }
    
    img->maxval = maxval;
    
    // Skip single whitespace after maxval
    fgetc(fp);
    
    // Read pixel data
    size_t pixel_count = img->width * img->height * 3;
    img->data.resize(pixel_count);
    
    if (maxval == 255) {
        // 8-bit PPM
        std::vector<uint8_t> buf(pixel_count);
        size_t read = fread(buf.data(), 1, pixel_count, fp);
        if (read != pixel_count) {
            std::cerr << "Failed to read all PPM pixel data (expected " << pixel_count 
                      << ", got " << read << ")" << std::endl;
            fclose(fp);
            delete img;
            return nullptr;
        }
        // Convert to 16-bit
        for (size_t i = 0; i < pixel_count; ++i) {
            img->data[i] = uint16_t(buf[i]) << 8;
        }
    } else {
        // 16-bit PPM (big-endian)
        for (size_t i = 0; i < pixel_count; ++i) {
            int hi = fgetc(fp);
            int lo = fgetc(fp);
            if (hi == EOF || lo == EOF) {
                std::cerr << "Failed to read all PPM pixel data" << std::endl;
                fclose(fp);
                delete img;
                return nullptr;
            }
            img->data[i] = (uint16_t(hi) << 8) | uint16_t(lo);
        }
    }
    
    fclose(fp);
    return img;
}

/**
 * Convert double [0,1] to uint16_t [0,65535]
 */
uint16_t double_to_uint16(double v) {
    if (v < 0.0) v = 0.0;
    if (v > 1.0) v = 1.0;
    return static_cast<uint16_t>(lrint(v * 65535.0));
}

/**
 * Compare RLE image with PPM ground truth
 * Returns true if images match (within tolerance)
 */
bool compare_images(const char* rle_file, const char* ppm_file, bool verbose = true) {
    if (verbose) {
        std::cout << "\n========================================" << std::endl;
        std::cout << "Comparing RLE with PPM ground truth" << std::endl;
        std::cout << "RLE: " << rle_file << std::endl;
        std::cout << "PPM: " << ppm_file << std::endl;
        std::cout << "========================================" << std::endl;
    }
    
    // Read RLE file
    FILE* rle_fp = fopen(rle_file, "rb");
    if (!rle_fp) {
        std::cerr << "Failed to open RLE file: " << rle_file << std::endl;
        return false;
    }
    icv_image_t* rle_img = rle_read(rle_fp);
    fclose(rle_fp);
    
    if (!rle_img) {
        std::cerr << "Failed to read RLE file" << std::endl;
        return false;
    }
    
    if (verbose) {
        std::cout << "\nRLE Image Info:" << std::endl;
        std::cout << "  Dimensions: " << rle_img->width << " x " << rle_img->height << std::endl;
        std::cout << "  Channels: " << rle_img->channels << std::endl;
        std::cout << "  Has Alpha: " << (rle_img->alpha_channel ? "Yes" : "No") << std::endl;
    }
    
    // Read PPM file
    PPMImage* ppm_img = read_ppm(ppm_file);
    if (!ppm_img) {
        std::cerr << "Failed to read PPM file" << std::endl;
        bu_free(rle_img->data, "image data");
        bu_free(rle_img, "image");
        return false;
    }
    
    if (verbose) {
        std::cout << "\nPPM Image Info:" << std::endl;
        std::cout << "  Dimensions: " << ppm_img->width << " x " << ppm_img->height << std::endl;
        std::cout << "  Maxval: " << ppm_img->maxval << std::endl;
    }
    
    // Check dimension match
    if (rle_img->width != ppm_img->width || rle_img->height != ppm_img->height) {
        std::cout << "\n*** DIMENSION MISMATCH ***" << std::endl;
        std::cout << "RLE: " << rle_img->width << " x " << rle_img->height << std::endl;
        std::cout << "PPM: " << ppm_img->width << " x " << ppm_img->height << std::endl;
        bu_free(rle_img->data, "image data");
        bu_free(rle_img, "image");
        delete ppm_img;
        return false;
    }
    
    // Compare pixels
    if (verbose) {
        std::cout << "\n=== Pixel Comparison ===" << std::endl;
    }
    
    uint64_t total_pixels = ppm_img->width * ppm_img->height;
    uint64_t differing_pixels = 0;
    uint64_t total_diff = 0;
    uint64_t max_diff = 0;
    
    // Tolerance: allow up to 1/256 difference (256 units in 16-bit space)
    const uint16_t TOLERANCE = 256;
    
    for (size_t y = 0; y < ppm_img->height; y++) {
        for (size_t x = 0; x < ppm_img->width; x++) {
            size_t rle_idx = (y * rle_img->width + x) * rle_img->channels;
            size_t ppm_idx = (y * ppm_img->width + x) * 3;
            
            uint16_t rle_r = double_to_uint16(rle_img->data[rle_idx]);
            uint16_t rle_g = double_to_uint16(rle_img->data[rle_idx + 1]);
            uint16_t rle_b = double_to_uint16(rle_img->data[rle_idx + 2]);
            
            uint16_t ppm_r = ppm_img->data[ppm_idx];
            uint16_t ppm_g = ppm_img->data[ppm_idx + 1];
            uint16_t ppm_b = ppm_img->data[ppm_idx + 2];
            
            uint64_t diff_r = abs(rle_r - ppm_r);
            uint64_t diff_g = abs(rle_g - ppm_g);
            uint64_t diff_b = abs(rle_b - ppm_b);
            uint64_t diff = diff_r + diff_g + diff_b;
            
            if (diff > TOLERANCE * 3) {
                differing_pixels++;
                total_diff += diff;
                if (diff > max_diff) {
                    max_diff = diff;
                }
                
                // Report first few mismatches
                if (verbose && differing_pixels <= 10) {
                    std::cout << "  Mismatch at (" << x << ", " << y << "): "
                              << "RLE=(" << rle_r << "," << rle_g << "," << rle_b << ") "
                              << "PPM=(" << ppm_r << "," << ppm_g << "," << ppm_b << ") "
                              << "Diff=" << diff << std::endl;
                }
            }
        }
    }
    
    if (verbose) {
        std::cout << "\nComparison Results:" << std::endl;
        std::cout << "  Total pixels compared: " << total_pixels << std::endl;
        std::cout << "  Differing pixels: " << differing_pixels 
                  << " (" << (100.0 * differing_pixels / total_pixels) << "%)" << std::endl;
        
        if (differing_pixels > 0) {
            double avg_diff = (double)total_diff / differing_pixels;
            std::cout << "  Average difference (per differing pixel): " << avg_diff << std::endl;
            std::cout << "  Maximum difference: " << max_diff << std::endl;
        }
    }
    
    bool match = (differing_pixels == 0);
    
    if (verbose) {
        if (match) {
            std::cout << "\n✓ PERFECT MATCH: RLE decoding matches PPM ground truth!" << std::endl;
        } else if (differing_pixels < total_pixels * 0.01) {
            std::cout << "\n✓ GOOD MATCH: Less than 1% of pixels differ" << std::endl;
        } else {
            std::cout << "\n✗ SIGNIFICANT DIFFERENCES: Decoder may have issues" << std::endl;
        }
    }
    
    // Cleanup
    bu_free(rle_img->data, "image data");
    bu_free(rle_img, "image");
    delete ppm_img;
    
    return match;
}

/**
 * Test roundtrip: RLE -> decode -> encode -> decode -> compare
 */
bool test_roundtrip(const char* rle_file, bool verbose = true) {
    if (verbose) {
        std::cout << "\n========================================" << std::endl;
        std::cout << "Testing roundtrip encode/decode" << std::endl;
        std::cout << "RLE: " << rle_file << std::endl;
        std::cout << "========================================" << std::endl;
    }
    
    // Read original RLE file
    FILE* fp = fopen(rle_file, "rb");
    if (!fp) {
        std::cerr << "Failed to open RLE file: " << rle_file << std::endl;
        return false;
    }
    icv_image_t* img1 = rle_read(fp);
    fclose(fp);
    
    if (!img1) {
        std::cerr << "Failed to read RLE file" << std::endl;
        return false;
    }
    
    if (verbose) {
        std::cout << "Original: " << img1->width << "x" << img1->height 
                  << " (" << img1->channels << " channels)" << std::endl;
    }
    
    // Re-encode
    std::string temp_file = std::string(rle_file) + ".roundtrip.rle";
    fp = fopen(temp_file.c_str(), "wb");
    if (!fp) {
        std::cerr << "Failed to create temp file" << std::endl;
        bu_free(img1->data, "image data");
        bu_free(img1, "image");
        return false;
    }
    
    int write_result = rle_write(img1, fp);
    fclose(fp);
    
    if (write_result != 0) {
        std::cerr << "Failed to write RLE file" << std::endl;
        bu_free(img1->data, "image data");
        bu_free(img1, "image");
        remove(temp_file.c_str());
        return false;
    }
    
    // Read back
    fp = fopen(temp_file.c_str(), "rb");
    if (!fp) {
        std::cerr << "Failed to read back temp file" << std::endl;
        bu_free(img1->data, "image data");
        bu_free(img1, "image");
        remove(temp_file.c_str());
        return false;
    }
    
    icv_image_t* img2 = rle_read(fp);
    fclose(fp);
    remove(temp_file.c_str());
    
    if (!img2) {
        std::cerr << "Failed to read back RLE file" << std::endl;
        bu_free(img1->data, "image data");
        bu_free(img1, "image");
        return false;
    }
    
    if (verbose) {
        std::cout << "Roundtrip: " << img2->width << "x" << img2->height 
                  << " (" << img2->channels << " channels)" << std::endl;
    }
    
    // Compare
    bool match = true;
    if (img1->width != img2->width || img1->height != img2->height || 
        img1->channels != img2->channels) {
        std::cerr << "Dimension/channel mismatch!" << std::endl;
        match = false;
    } else {
        size_t total_values = img1->width * img1->height * img1->channels;
        uint64_t diff_count = 0;
        
        for (size_t i = 0; i < total_values; i++) {
            double diff = std::abs(img1->data[i] - img2->data[i]);
            if (diff > 0.01) {
                diff_count++;
                if (verbose && diff_count <= 5) {
                    size_t pixel_idx = i / img1->channels;
                    size_t channel = i % img1->channels;
                    size_t y = pixel_idx / img1->width;
                    size_t x = pixel_idx % img1->width;
                    std::cout << "  Difference at (" << x << "," << y << ") channel " << channel
                              << ": " << img1->data[i] << " vs " << img2->data[i] << std::endl;
                }
            }
        }
        
        if (diff_count > 0) {
            std::cout << "  Total differences: " << diff_count << " / " << total_values 
                      << " (" << (100.0 * diff_count / total_values) << "%)" << std::endl;
            match = false;
        }
    }
    
    if (verbose) {
        if (match) {
            std::cout << "✓ ROUNDTRIP SUCCESS: Encode/decode preserves data!" << std::endl;
        } else {
            std::cout << "✗ ROUNDTRIP FAILED: Data not preserved!" << std::endl;
        }
    }
    
    bu_free(img1->data, "image data");
    bu_free(img1, "image");
    bu_free(img2->data, "image data");
    bu_free(img2, "image");
    
    return match;
}

int main(int argc, char** argv) {
    std::cout << "========================================" << std::endl;
    std::cout << "RLE Ground Truth Verification" << std::endl;
    std::cout << "Testing against ImageMagick PPM files" << std::endl;
    std::cout << "========================================" << std::endl;
    
    struct TestPair {
        const char* rle;
        const char* ppm;
    };
    
    TestPair tests[] = {
        {"imgs/lenna.rle", "imgs/lenna.ppm"},
        {"imgs/dart.rle", "imgs/dart.ppm"},
        {"imgs/tack_w_shadow.rle", "imgs/tack_w_shadow.ppm"}
    };
    
    int total = 0;
    int passed = 0;
    int failed = 0;
    
    // Test 1: Decode and compare with ground truth
    std::cout << "\n=== PHASE 1: Decode Verification ===" << std::endl;
    for (const auto& test : tests) {
        total++;
        std::cout << "\n--- Test " << total << " ---" << std::endl;
        if (compare_images(test.rle, test.ppm, true)) {
            passed++;
            std::cout << "RESULT: PASSED" << std::endl;
        } else {
            failed++;
            std::cout << "RESULT: FAILED" << std::endl;
        }
    }
    
    // Test 2: Roundtrip testing
    std::cout << "\n\n=== PHASE 2: Roundtrip Verification ===" << std::endl;
    for (const auto& test : tests) {
        total++;
        std::cout << "\n--- Test " << total << " ---" << std::endl;
        if (test_roundtrip(test.rle, true)) {
            passed++;
            std::cout << "RESULT: PASSED" << std::endl;
        } else {
            failed++;
            std::cout << "RESULT: FAILED" << std::endl;
        }
    }
    
    // Test 3: Re-encode and compare with PPM
    std::cout << "\n\n=== PHASE 3: Re-encode and Compare ===" << std::endl;
    for (const auto& test : tests) {
        total++;
        std::cout << "\n--- Test " << total << " ---" << std::endl;
        
        // Read original
        FILE* fp = fopen(test.rle, "rb");
        if (!fp) {
            std::cerr << "Failed to open: " << test.rle << std::endl;
            failed++;
            continue;
        }
        icv_image_t* img = rle_read(fp);
        fclose(fp);
        
        if (!img) {
            std::cerr << "Failed to read: " << test.rle << std::endl;
            failed++;
            continue;
        }
        
        // Re-encode
        std::string temp_file = std::string(test.rle) + ".reencoded.rle";
        fp = fopen(temp_file.c_str(), "wb");
        if (!fp) {
            std::cerr << "Failed to create temp file" << std::endl;
            bu_free(img->data, "image data");
            bu_free(img, "image");
            failed++;
            continue;
        }
        
        int write_result = rle_write(img, fp);
        fclose(fp);
        bu_free(img->data, "image data");
        bu_free(img, "image");
        
        if (write_result != 0) {
            std::cerr << "Failed to write RLE file" << std::endl;
            remove(temp_file.c_str());
            failed++;
            continue;
        }
        
        // Compare re-encoded with PPM
        if (compare_images(temp_file.c_str(), test.ppm, true)) {
            passed++;
            std::cout << "RESULT: PASSED" << std::endl;
        } else {
            failed++;
            std::cout << "RESULT: FAILED" << std::endl;
        }
        
        remove(temp_file.c_str());
    }
    
    // Summary
    std::cout << "\n\n========================================" << std::endl;
    std::cout << "SUMMARY" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << "Total tests: " << total << std::endl;
    std::cout << "Passed: " << passed << " (" << (100 * passed / total) << "%)" << std::endl;
    std::cout << "Failed: " << failed << " (" << (100 * failed / total) << "%)" << std::endl;
    std::cout << "========================================" << std::endl;
    
    return (failed == 0) ? 0 : 1;
}
