.TH RLETORAW 1 "1990" 1
.UC 4 
.SH NAME
rletoraw \- Convert RLE file to raw RGB form.
.SH SYNOPSIS
.B rletoraw
[
.B \-o 
.I outfile
] [
.I infile
]
.SH DESCRIPTION
This program converts an
.IR RLE (5)
image to a raw RGB form.  The output file is a stream of pixels
(RGBRGB...), in left-to-right, bottom-to-top order.  The width and
height of the input image will be printed on the standard error
stream.
.SH OPTIONS
.TP
.BI \-o \ outfile
If specified, the output will be written to this file.  If 
.I outfile
is "\-", or if it is not specified, the output will be written to the
standard output stream.
.TP
.I infile
The input will be read from this file.  If
.I infile
is "\-" or is not specified, the input will be read from the standard
input stream.
.SH SEE ALSO
.IR rawtorle (1),
.IR urt (1),
.IR RLE (5).
.SH AUTHOR
Martin Friedmann
.SH BUGS
Input files must have red, green, and blue channels.  If not, bogus
data will be generated in the missing colors.
