#
# Makefile for include subdirectory.
# 
# Only thing to do here is install the .h files somewhere if INC_DEST is
# set.
#

# No default action.
default:

#ifdef INC_DEST
#set DEST INC_DEST
DEST =
#endif

HDRS = \
	exit_status.h \
	pyramid.h \
	rle.h \
	rle_code.h \
	rle_put.h \
	rle_raw.h 

install: $(HDRS)
	@sh -c "if test 'x$(DEST)' != x ; then \
		if test 'x$(HDRS)' != x ; then eval \
			'for hdr in $?; do \
				echo cp \$$hdr $(DEST)/\$$hdr ; \
				cp \$$hdr $(DEST)/\$$hdr; \
			done' ; \
		else \
		    true ; \
		fi ; \
	else \
		true ; \
	fi"
	touch install

# Nothing to clean
clean:

# Remove installed headers
pristine:
	@-if test "x$(DEST)" != x ; then eval \
		'for hdr in $(HDRS); do \
			echo rm -f $(DEST)/$$hdr; \
			rm -f $(DEST)/$$hdr; \
		done' ; \
	else \
		true ; \
	fi
	rm -f install

