# Makefile for get/getx11 directory

# Default thing to make is everything
default: all

#set	DEST	GET_DEST	Where to install it.
DEST = ../../../bin

#add			DIRFLAGS	$(INCX11)
#ifnadd	XLIBINT_H	DIRFLAGS	-DXLIBINT_H_NOT_AVAILABLE
#emit DIRFLAGS
DIRFLAGS =

# -lX11 is X11 support library
DIRLIBS = $(LIBX11) -lm

# Executables.  The .out will be stripped off in the install action.

X_C_FILES =\
	getx11.c x11_stuff.c timer.c map_scan.c in_cmap.c XCopyImg.c

X_O_FILES =\
	getx11.o x11_stuff.o timer.o map_scan.o in_cmap.o XCopyImg.o

PGMS = getx11.out

all: $(PGMS)

x11_stuff.o: XGetHClrs.c

# getx11 - read RLE file to X11 display
getx11.out: $(X_O_FILES) 
	${CC} $(CFLAGS) $(X_O_FILES) $(LIBS) -o getx11.new
	mv getx11.new getx11.out

# Incremental install, copies executable to DEST dir.
install: default install-pgm
	touch install

# Clean up binaries
clean:	clean-pgm

# Clean up installed code
pristine: pristine-pgm
